In [1]:
import torch
import numpy as np

In [4]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [7]:
# compatible with numpy array
np_array = np.array(data)
x_np = torch.tensor(np_array)
x_np2 = torch.from_numpy(np_array)
x_np, x_np2

(tensor([[1, 2],
         [3, 4]]),
 tensor([[1, 2],
         [3, 4]]))

In [9]:
x_data.shape, x_np.shape

(torch.Size([2, 2]), torch.Size([2, 2]))

In [10]:
# Retains the properties of x_data e.g) retains shape
# but change every entry to 1
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [13]:
# Retains the properties of x_data
# but change every entry to randomised data
x_rand = torch.rand_like(x_data)  # ERROR!
x_rand

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [14]:
# Must override the datatype of x_data: float
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_rand

tensor([[0.1631, 0.6977],
        [0.7419, 0.8283]])

In [17]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
rand_tensor

tensor([[0.0255, 0.6369, 0.9646],
        [0.9964, 0.5512, 0.4746]])

In [18]:
ones_tensor = torch.ones(shape)
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [20]:
zeros_tensor = torch.zeros(shape)
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [21]:
## Tensor Attributes ##

In [23]:
tensor = torch.rand(3, 4)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)
tensor

torch.Size([3, 4])
torch.float32
cpu


tensor([[0.4477, 0.9725, 0.4603, 0.9354],
        [0.5483, 0.6573, 0.6367, 0.5844],
        [0.6797, 0.5668, 0.9768, 0.2024]])

In [26]:
## Check if GPU is available ##
print(torch.cuda.is_available())

if torch.cuda.is_available():
    tensor = tensor.to('cuda')

False


In [28]:
## Indexing, slicing, joining and multiplying like numpy ##

In [ ]:
# Indexing and slicing

In [48]:
tensor = torch.rand(4, 4)
tensor

tensor([[0.8635, 0.4430, 0.1307, 0.6370],
        [0.1044, 0.5282, 0.4938, 0.5815],
        [0.2658, 0.2232, 0.7220, 0.2865],
        [0.4285, 0.8710, 0.5060, 0.3809]])

In [49]:
tensor[1], tensor[:, 1]

(tensor([0.1044, 0.5282, 0.4938, 0.5815]),
 tensor([0.4430, 0.5282, 0.2232, 0.8710]))

In [50]:
tensor[:, 1] = 0
tensor

tensor([[0.8635, 0.0000, 0.1307, 0.6370],
        [0.1044, 0.0000, 0.4938, 0.5815],
        [0.2658, 0.0000, 0.7220, 0.2865],
        [0.4285, 0.0000, 0.5060, 0.3809]])

In [51]:
# Joining tensors: torch.cat()

In [58]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1.shape)
t1

torch.Size([4, 12])


tensor([[0.8635, 0.0000, 0.1307, 0.6370, 0.8635, 0.0000, 0.1307, 0.6370, 0.8635,
         0.0000, 0.1307, 0.6370],
        [0.1044, 0.0000, 0.4938, 0.5815, 0.1044, 0.0000, 0.4938, 0.5815, 0.1044,
         0.0000, 0.4938, 0.5815],
        [0.2658, 0.0000, 0.7220, 0.2865, 0.2658, 0.0000, 0.7220, 0.2865, 0.2658,
         0.0000, 0.7220, 0.2865],
        [0.4285, 0.0000, 0.5060, 0.3809, 0.4285, 0.0000, 0.5060, 0.3809, 0.4285,
         0.0000, 0.5060, 0.3809]])

In [59]:
t2 = torch.cat([tensor, tensor, tensor], dim=0)
print(t2.shape)
t2

torch.Size([12, 4])


tensor([[0.8635, 0.0000, 0.1307, 0.6370],
        [0.1044, 0.0000, 0.4938, 0.5815],
        [0.2658, 0.0000, 0.7220, 0.2865],
        [0.4285, 0.0000, 0.5060, 0.3809],
        [0.8635, 0.0000, 0.1307, 0.6370],
        [0.1044, 0.0000, 0.4938, 0.5815],
        [0.2658, 0.0000, 0.7220, 0.2865],
        [0.4285, 0.0000, 0.5060, 0.3809],
        [0.8635, 0.0000, 0.1307, 0.6370],
        [0.1044, 0.0000, 0.4938, 0.5815],
        [0.2658, 0.0000, 0.7220, 0.2865],
        [0.4285, 0.0000, 0.5060, 0.3809]])